# uncompyle6 version 3.9.1
# Python bytecode version base 3.7.0 (3394)
# Decompiled from: Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
# Embedded file name: output/Live/mac_universal_64_static/Release/python-bundle/MIDI Remote Scripts/UC33e/consts.py
# Compiled at: 2024-03-09 01:30:22
# Size of source mod 2**32: 2326 bytes
from __future__ import absolute_import, print_function, unicode_literals
ID_REQUEST = 0
ID_RESP = 0
GENERIC_STOP = -1
GENERIC_PLAY = -1
GENERIC_REC = -1
GENERIC_LOOP = -1
GENERIC_RWD = -1
GENERIC_FFWD = -1
GENERIC_TRANSPORT = (
 GENERIC_STOP,
 GENERIC_PLAY,
 GENERIC_REC,
 GENERIC_LOOP,
 GENERIC_RWD,
 GENERIC_FFWD)
GENERIC_ENC1 = 13
GENERIC_ENC2 = 13
GENERIC_ENC3 = 13
GENERIC_ENC4 = 13
GENERIC_ENC5 = 13
GENERIC_ENC6 = 13
GENERIC_ENC7 = 13
GENERIC_ENC8 = 13
GENERIC_ENCODERS = (
 GENERIC_ENC1,
 GENERIC_ENC2,
 GENERIC_ENC3,
 GENERIC_ENC4,
 GENERIC_ENC5,
 GENERIC_ENC6,
 GENERIC_ENC7,
 GENERIC_ENC8)
GENERIC_SLI1 = 7
GENERIC_SLI2 = 7
GENERIC_SLI3 = 7
GENERIC_SLI4 = 7
GENERIC_SLI5 = 7
GENERIC_SLI6 = 7
GENERIC_SLI7 = 7
GENERIC_SLI8 = 7
GENERIC_SLIDERS = (
 GENERIC_SLI1,
 GENERIC_SLI2,
 GENERIC_SLI3,
 GENERIC_SLI4,
 GENERIC_SLI5,
 GENERIC_SLI6,
 GENERIC_SLI7,
 GENERIC_SLI8)
GENERIC_BUT1 = -1
GENERIC_BUT2 = -1
GENERIC_BUT3 = -1
GENERIC_BUT4 = -1
GENERIC_BUT5 = -1
GENERIC_BUT6 = -1
GENERIC_BUT7 = -1
GENERIC_BUT8 = -1
GENERIC_BUT9 = -1
GENERIC_BUTTONS = (
 GENERIC_BUT1,
 GENERIC_BUT2,
 GENERIC_BUT3,
 GENERIC_BUT4,
 GENERIC_BUT5,
 GENERIC_BUT6,
 GENERIC_BUT7,
 GENERIC_BUT8)
GENERIC_PAD1 = -1
GENERIC_PAD2 = -1
GENERIC_PAD3 = -1
GENERIC_PAD4 = -1
GENERIC_PAD5 = -1
GENERIC_PAD6 = -1
GENERIC_PAD7 = -1
GENERIC_PAD8 = -1
GENERIC_PADS = (
 GENERIC_PAD1,
 GENERIC_PAD2,
 GENERIC_PAD3,
 GENERIC_PAD4,
 GENERIC_PAD5,
 GENERIC_PAD6,
 GENERIC_PAD7,
 GENERIC_PAD8)
